### ISSUE TITLE
Unable to successfully build - auto-bind cannot minify

### ISSUE THREAD

**Issue by Rangoons** [sindresorhus/react-extras#6]
Terminal output:

Failed to minify the code from this file:

        ./node_modules/auto-bind/index.js:2

Read more here: http://bit.ly/2tRViJ9

**Comment by sindresorhus** [comment]
I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
