### ISSUE TITLE
I think the render prop of the `<For>` component should be required

### ISSUE THREAD

**Issue by alessandroHenrique** [sindresorhus/react-extras#9]
The way the **For** component is defined [here](https://github.com/sindresorhus/react-extras/blob/master/index.js#L52), is the user does not pass a `render` prop, it's going to appear a horrible syntax error in the console. 

By placing `isRequired` for the render prop in the PropTypes of the `For` component, the console will show a nice error that the user did not pass the render function.

Do you think it's a valid issue? if yes, I'd like to contribute. =)

**Comment by sindresorhus** [comment]
Yes, that's an oversight. PR welcome :)
